package com.aritxonly.deadliner.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

object DeadlinerMaterial3ColorSchemeFactory {
    fun create(
        tokens: DeadlinerColorTokens,
        darkTheme: Boolean,
    ): ColorScheme = if (darkTheme) {
        darkColorScheme(
            primary = tokens.primary,
            onPrimary = tokens.onPrimary,
            primaryContainer = tokens.primaryContainer,
            onPrimaryContainer = tokens.onPrimaryContainer,
            inversePrimary = tokens.inversePrimary,
            secondary = tokens.secondary,
            onSecondary = tokens.onSecondary,
            secondaryContainer = tokens.secondaryContainer,
            onSecondaryContainer = tokens.onSecondaryContainer,
            tertiary = tokens.tertiary,
            onTertiary = tokens.onTertiary,
            tertiaryContainer = tokens.tertiaryContainer,
            onTertiaryContainer = tokens.onTertiaryContainer,
            background = tokens.background,
            onBackground = tokens.onBackground,
            surface = tokens.surface,
            onSurface = tokens.onSurface,
            surfaceVariant = tokens.surfaceVariant,
            onSurfaceVariant = tokens.onSurfaceVariant,
            surfaceTint = tokens.primary,
            inverseSurface = tokens.onSurface,
            inverseOnSurface = tokens.surface,
            error = tokens.error,
            onError = tokens.onError,
            errorContainer = tokens.errorContainer,
            onErrorContainer = tokens.onErrorContainer,
            outline = tokens.outline,
            outlineVariant = tokens.outlineVariant,
            scrim = tokens.scrim,
            surfaceBright = tokens.surfaceBright,
            surfaceContainer = tokens.surfaceContainer,
            surfaceContainerHigh = tokens.surfaceContainerHigh,
            surfaceContainerHighest = tokens.surfaceContainerHighest,
            surfaceContainerLow = tokens.surfaceContainerLow,
            surfaceContainerLowest = tokens.surfaceContainerLowest,
            surfaceDim = tokens.surfaceDim,
            primaryFixed = tokens.primaryContainer,
            primaryFixedDim = tokens.primary,
            onPrimaryFixed = tokens.onPrimaryContainer,
            onPrimaryFixedVariant = tokens.onPrimary,
            secondaryFixed = tokens.secondaryContainer,
            secondaryFixedDim = tokens.secondary,
            onSecondaryFixed = tokens.onSecondaryContainer,
            onSecondaryFixedVariant = tokens.onSecondary,
            tertiaryFixed = tokens.tertiaryContainer,
            tertiaryFixedDim = tokens.tertiary,
            onTertiaryFixed = tokens.onTertiaryContainer,
            onTertiaryFixedVariant = tokens.onTertiary,
        )
    } else {
        lightColorScheme(
            primary = tokens.primary,
            onPrimary = tokens.onPrimary,
            primaryContainer = tokens.primaryContainer,
            onPrimaryContainer = tokens.onPrimaryContainer,
            inversePrimary = tokens.inversePrimary,
            secondary = tokens.secondary,
            onSecondary = tokens.onSecondary,
            secondaryContainer = tokens.secondaryContainer,
            onSecondaryContainer = tokens.onSecondaryContainer,
            tertiary = tokens.tertiary,
            onTertiary = tokens.onTertiary,
            tertiaryContainer = tokens.tertiaryContainer,
            onTertiaryContainer = tokens.onTertiaryContainer,
            background = tokens.background,
            onBackground = tokens.onBackground,
            surface = tokens.surface,
            onSurface = tokens.onSurface,
            surfaceVariant = tokens.surfaceVariant,
            onSurfaceVariant = tokens.onSurfaceVariant,
            surfaceTint = tokens.primary,
            inverseSurface = tokens.onSurface,
            inverseOnSurface = tokens.surface,
            error = tokens.error,
            onError = tokens.onError,
            errorContainer = tokens.errorContainer,
            onErrorContainer = tokens.onErrorContainer,
            outline = tokens.outline,
            outlineVariant = tokens.outlineVariant,
            scrim = tokens.scrim,
            surfaceBright = tokens.surfaceBright,
            surfaceContainer = tokens.surfaceContainer,
            surfaceContainerHigh = tokens.surfaceContainerHigh,
            surfaceContainerHighest = tokens.surfaceContainerHighest,
            surfaceContainerLow = tokens.surfaceContainerLow,
            surfaceContainerLowest = tokens.surfaceContainerLowest,
            surfaceDim = tokens.surfaceDim,
            primaryFixed = tokens.primaryContainer,
            primaryFixedDim = tokens.primary,
            onPrimaryFixed = tokens.onPrimaryContainer,
            onPrimaryFixedVariant = tokens.onPrimary,
            secondaryFixed = tokens.secondaryContainer,
            secondaryFixedDim = tokens.secondary,
            onSecondaryFixed = tokens.onSecondaryContainer,
            onSecondaryFixedVariant = tokens.onSecondary,
            tertiaryFixed = tokens.tertiaryContainer,
            tertiaryFixedDim = tokens.tertiary,
            onTertiaryFixed = tokens.onTertiaryContainer,
            onTertiaryFixedVariant = tokens.onTertiary,
        )
    }
}
