package com.aritxonly.deadliner.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver
import top.yukonga.miuix.kmp.theme.Colors
import top.yukonga.miuix.kmp.theme.darkColorScheme as darkMiuixColorScheme
import top.yukonga.miuix.kmp.theme.lightColorScheme as lightMiuixColorScheme

object DeadlinerMiuixColorSchemeFactory {
    fun create(
        tokens: DeadlinerColorTokens,
        darkTheme: Boolean,
    ): Colors {
        val sliderBackground = tokens.outlineVariant
            .copy(alpha = if (darkTheme) 0.48f else 0.28f)
            .compositeOver(tokens.surfaceContainerHigh)

        return if (darkTheme) {
        darkMiuixColorScheme(
            primary = tokens.primary,
            onPrimary = tokens.onPrimary,
            primaryVariant = tokens.inversePrimary,
            onPrimaryVariant = tokens.onPrimaryContainer,
            error = tokens.error,
            onError = tokens.onError,
            errorContainer = tokens.errorContainer,
            onErrorContainer = tokens.onErrorContainer,
            disabledPrimary = tokens.primary.copy(alpha = 0.45f),
            disabledOnPrimary = tokens.onPrimary.copy(alpha = 0.6f),
            disabledPrimaryButton = tokens.primary.copy(alpha = 0.45f),
            disabledOnPrimaryButton = tokens.onPrimary.copy(alpha = 0.6f),
            disabledPrimarySlider = tokens.primary.copy(alpha = 0.55f),
            primaryContainer = tokens.primaryContainer,
            onPrimaryContainer = tokens.onPrimaryContainer,
            secondary = tokens.secondary,
            onSecondary = tokens.onSecondary,
            secondaryVariant = tokens.tertiary,
            onSecondaryVariant = tokens.onTertiary,
            disabledSecondary = tokens.secondary.copy(alpha = 0.45f),
            disabledOnSecondary = tokens.onSecondary.copy(alpha = 0.6f),
            disabledSecondaryVariant = tokens.tertiary.copy(alpha = 0.45f),
            disabledOnSecondaryVariant = tokens.onTertiary.copy(alpha = 0.6f),
            secondaryContainer = tokens.secondaryContainer,
            onSecondaryContainer = tokens.onSecondaryContainer,
            secondaryContainerVariant = tokens.surfaceContainerHigh,
            onSecondaryContainerVariant = tokens.onSurfaceVariant,
            tertiaryContainer = tokens.tertiaryContainer,
            onTertiaryContainer = tokens.onTertiaryContainer,
            tertiaryContainerVariant = tokens.surfaceContainerHighest,
            background = tokens.background,
            onBackground = tokens.onBackground,
            onBackgroundVariant = tokens.onBackgroundVariant,
            surface = tokens.surface,
            onSurface = tokens.onSurface,
            surfaceVariant = tokens.surfaceVariant,
            onSurfaceSecondary = tokens.onSurface.copy(alpha = 0.8f),
            onSurfaceVariantSummary = tokens.onSurfaceVariantSummary,
            onSurfaceVariantActions = tokens.onSurfaceVariantActions,
            disabledOnSurface = tokens.onSurfaceVariant.copy(alpha = 0.5f),
            surfaceContainer = tokens.surfaceContainer,
            onSurfaceContainer = tokens.onSurface,
            onSurfaceContainerVariant = tokens.onSurfaceVariant,
            surfaceContainerHigh = tokens.surfaceContainerHigh,
            onSurfaceContainerHigh = tokens.onSurface,
            surfaceContainerHighest = tokens.surfaceContainerHighest,
            onSurfaceContainerHighest = tokens.onSurface,
            outline = tokens.outline,
            dividerLine = tokens.outlineVariant,
            windowDimming = tokens.scrim,
            sliderKeyPoint = tokens.outlineVariant.copy(alpha = 0.35f),
            sliderKeyPointForeground = tokens.primary,
            sliderBackground = sliderBackground,
        )
    } else {
        lightMiuixColorScheme(
            primary = tokens.primary,
            onPrimary = tokens.onPrimary,
            primaryVariant = tokens.inversePrimary,
            onPrimaryVariant = tokens.onPrimaryContainer,
            error = tokens.error,
            onError = tokens.onError,
            errorContainer = tokens.errorContainer,
            onErrorContainer = tokens.onErrorContainer,
            disabledPrimary = tokens.primary.copy(alpha = 0.45f),
            disabledOnPrimary = tokens.onPrimary.copy(alpha = 0.6f),
            disabledPrimaryButton = tokens.primary.copy(alpha = 0.45f),
            disabledOnPrimaryButton = tokens.onPrimary.copy(alpha = 0.6f),
            disabledPrimarySlider = tokens.primary.copy(alpha = 0.55f),
            primaryContainer = tokens.primaryContainer,
            onPrimaryContainer = tokens.onPrimaryContainer,
            secondary = tokens.secondary,
            onSecondary = tokens.onSecondary,
            secondaryVariant = tokens.tertiary,
            onSecondaryVariant = tokens.onTertiary,
            disabledSecondary = tokens.secondary.copy(alpha = 0.45f),
            disabledOnSecondary = tokens.onSecondary.copy(alpha = 0.6f),
            disabledSecondaryVariant = tokens.tertiary.copy(alpha = 0.45f),
            disabledOnSecondaryVariant = tokens.onTertiary.copy(alpha = 0.6f),
            secondaryContainer = tokens.secondaryContainer,
            onSecondaryContainer = tokens.onSecondaryContainer,
            secondaryContainerVariant = tokens.surfaceContainerHigh,
            onSecondaryContainerVariant = tokens.onSurfaceVariant,
            tertiaryContainer = tokens.tertiaryContainer,
            onTertiaryContainer = tokens.onTertiaryContainer,
            tertiaryContainerVariant = tokens.surfaceContainerHighest,
            background = tokens.background,
            onBackground = tokens.onBackground,
            onBackgroundVariant = tokens.onBackgroundVariant,
            surface = tokens.surface,
            onSurface = tokens.onSurface,
            surfaceVariant = tokens.surfaceVariant,
            onSurfaceSecondary = tokens.onSurface.copy(alpha = 0.8f),
            onSurfaceVariantSummary = tokens.onSurfaceVariantSummary,
            onSurfaceVariantActions = tokens.onSurfaceVariantActions,
            disabledOnSurface = tokens.onSurfaceVariant.copy(alpha = 0.5f),
            surfaceContainer = tokens.surfaceContainer,
            onSurfaceContainer = tokens.onSurface,
            onSurfaceContainerVariant = tokens.onSurfaceVariant,
            surfaceContainerHigh = tokens.surfaceContainerHigh,
            onSurfaceContainerHigh = tokens.onSurface,
            surfaceContainerHighest = tokens.surfaceContainerHighest,
            onSurfaceContainerHighest = tokens.onSurface,
            outline = tokens.outline,
            dividerLine = tokens.outlineVariant,
            windowDimming = tokens.scrim,
            sliderKeyPoint = tokens.outlineVariant.copy(alpha = 0.35f),
            sliderKeyPointForeground = tokens.primary,
            sliderBackground = sliderBackground,
        )
    }
    }
}
